# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  gateway:
    build: gateway
    # образ, из которого должен быть запущен контейнер
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    # образ, из которого должен быть запущен контейнер
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
#      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit://db:5432/shareit
      - SPRING_DATASOURCE_USER=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_DATASOURCE_DB_HOST=db
      - SPRING_DATASOURCE_DB_PORT=5432
      - SPRING_DATASOURCE_DB_NAME=shareit

  db:
    image:  postgres:15.1-alpine
#    image:  1000kit/h2
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


