SET
REFERENTIAL_INTEGRITY = FALSE;
truncate table USERS;
SET
REFERENTIAL_INTEGRITY = TRUE;

ALTER SEQUENCE users_sequence RESTART WITH 1;


SET
REFERENTIAL_INTEGRITY = FALSE;
truncate table items;
SET
REFERENTIAL_INTEGRITY = TRUE;

ALTER SEQUENCE items_id_seq RESTART WITH 1;


SET
REFERENTIAL_INTEGRITY = FALSE;
truncate table bookings;
SET
REFERENTIAL_INTEGRITY = TRUE;

ALTER SEQUENCE booking_id_seq RESTART WITH 1;
